name: Deploy Notebook to Dev Environment
# A github action to deploy a notebook to a specific environment
# uses the template/deploy_notebook_to_env.yml file
on:
  push:
    branches:
      - dev      
# This will have a single job that will run the deploy_notebook_to_env.yml file
jobs:
  deploy:
    # run the template/deploy_notebook_to_env.yml file
    uses: temp_deploy_notebook_to_env.yml
    # pass the environment name as an argument
    with:
      environment: dev
