# A github action to deploy a notebook to a specific environment
# uses the template/deploy_notebook_to_env.yml file

name: Deploy Notebook to Dev Environment

on:
  push:
    branches:
      - dev
      
jobs:
  deploy_notebook:
    name: Deploy Notebook to Dev Environment
    uses: ./.github/workflows/template/deploy_notebook_to_env.yml
    with:
      SNOWFLAKE_ENV: dev
      SNOWFLAKE_NOTEBOOK_PATH: '@"REPO_NOTEBOOKS"."PUBLIC"."NOTEBOOKS"/branches/dev/Notebooks/DemoCount/Working with Git.ipynb'
      SNOWFLAKE_NOTEBOOK_NAME: example_notebook_from_cicd
      SNOWFLAKE_NOTEBOOK_VERSION: 1.0.0
      SNOWFLAKE_NOTEBOOK_COMMENT: "Deploying example notebook to dev environment"
      SNOWFLAKE_NOTEBOOK_TAGS: "example, notebook, dev"
